on:
  workflow_dispatch:  # Allows you to trigger the workflow manually

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Comment on all open PRs
        run: |
          PRS=$(gh pr list --state open --json number -q '.[].number')
          for PR in $PRS; do
            gh pr comment $PR --body "Hey!! Nice job on your hackpad submission. This is alexren // @qcoral sending this automation to let you know that the submission guidelines have been updated, please follow https://hackpad.hackclub.com/submitting again. Sorry for the confusion!! Hopefully this won't be needed again."
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
